### ISSUE TITLE
Missing CLI flags

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OMFMISimulator-testsuite#21]
The command-line version of OMSimulator lacks the following flags needed for good regression testing:
- [x] alarm (to kill the process on a timeout)
- [x] Number of output intervals (or step size) for the output file (linear interpolation in the result-file makes verifying results hard)

**Comment by lochel** [comment]
@sjoelund You are right, the alarm functionality is needed. However, I don't know how to implement it properly.
